name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  build:
    name: build
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup show
      - name: Build
        run: cargo build
